RailsApp/config/routes.rb
Rails.application.routes.draw do
  resources :board_messages
  resources :board_users
  resources :data_pages
  devise_for :accounts
  get 'ajax/index'
  get 'ajax/data'
  post 'ajax/data'
  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  resources :mycontacts

  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'

  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'


  get 'messages/index'
  get 'messages', to: 'messages#index'
  get 'messages/add'
  post 'messages/add', to: 'messages#create'
  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'
  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'
  get 'cards/add'
  post 'cards/add'
  get 'cards/:id', to: 'cards#show'
  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'
  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/find'
  post 'people/find'
  get 'people/delete/:id', to: 'people#delete'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people', to: 'people#index'
  get 'people/index'
  get 'people/:id', to: 'people#show'

  get 'dengonban/index'
  post 'dengonban/index'
  get 'dengonban', to: 'dengonban#index'
  post 'dengonban', to: 'dengonban#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'helo/index'
  get 'helo', to: 'helo#index'
  get 'helo/other'
  post 'helo', to: 'helo#index'
  post 'helo/index'
  get 'helo/login_check'
end

RailsApp/app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

RailsApp/app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question

    validates :content, :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
    validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
    has_many :blogpost

    validates :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :bloggenre

    validates :title, :content, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/board_user.rb
class BoardUser < ApplicationRecord
    belongs_to :account
    has_many :board_message

    validates :nickname, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/card.rb
class Card < ApplicationRecord
end

RailsApp/app/models/data_page.rb
class DataPage < ApplicationRecord
end

RailsApp/app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator

    def validate_each(record, attribute, value)
        unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            record.errors[attribute] << (options[:message] || "is not an email")
        end
    end
end

RailsApp/app/models/message.rb
class Message < ApplicationRecord
    validates :message, presence: {message:'を書いてください。'}
end

RailsApp/app/models/mycontact.rb
class Mycontact < ApplicationRecord
    validates :name, presence: {message:'は、必須項目です。'}
    validates :age, numericality: {message:'は、数字で入力ください。'}
    validates :nationality, inclusion: {in: [true, false], message:'は、真偽値です。'}
end

RailsApp/app/models/person.rb
class Person < ApplicationRecord
    has_many :message

    validates :name, presence: {message: 'は、必須項目です。' }
    validates :age, numericality: {message: 'は、数字で入力ください。'}
    validates :mail, email: {message: 'はメールアドレスではありません。'}
end

RailsApp/app/models/question.rb
class Question < ApplicationRecord
    has_many :answer

    validates :content, :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/questionary.rb
class Questionary < ApplicationRecord
    has_many :questionary_item
    has_many :questionary_result

    validates :title, :description, :deadline, presence: {message:'は、必須項目です。'}
end

RailsApp/app/controllers/questionaries_controller.rb
class QuestionariesController < ApplicationController
  before_action :set_questionary, only: [:show, :edit, :update, :destroy]

  # GET /questionaries
  # GET /questionaries.json
  def index
    @questionaries = Questionary.all.order('created_at desc')
  end

  # GET /questionaries/1
  # GET /questionaries/1.json
  def show
  end

  def sendform
    id = params[:id]
    result = 'question_id + id'
    for i in 1..100
      str = 'r' + i.to_s
      if params[str] == nil then
        result += ',' + str + ':0'
      else
        result += ',' + str + ':' + params[str]
      end
    end
    obj = QuestionaryResult.new
    obj.questionary_id = id
    obj.result = result
    obj.save!
    redirect_to '/questionaries'
  end

  # GET /questionaries/new
  def new
    @questionary = Questionary.new
  end

  # GET /questionaries/1/edit
  def edit
  end

  # POST /questionaries
  # POST /questionaries.json
  def create
    @questionary = Questionary.new(questionary_params)

    respond_to do |format|
      if @questionary.save
        format.html { redirect_to '/questionary_items/new/' + @questionary.id.to_s }
        format.json { render :show, status: :created, location: @questionary }
      else
        format.html { render :new }
        format.json { render json: @questionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionaries/1
  # PATCH/PUT /questionaries/1.json
  def update
    respond_to do |format|
      if @questionary.update(questionary_params)
        format.html { redirect_to @questionary, notice: 'Questionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @questionary }
      else
        format.html { render :edit }
        format.json { render json: @questionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionaries/1
  # DELETE /questionaries/1.json
  def destroy
    @questionary.destroy
    respond_to do |format|
      format.html { redirect_to questionaries_url, notice: 'Questionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionary
      @questionary = Questionary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionary_params
      params.require(:questionary).permit(:title, :description, :deadline)
    end
end

RailsApp/app/helpers/ajax_helper.rb
module AjaxHelper
end

RailsApp/app/helpers/answers_helper.rb
module AnswersHelper
end

RailsApp/app/helpers/blogs_helper.rb
module BlogsHelper
end

RailsApp/app/helpers/cards_helper.rb
module CardsHelper
end

RailsApp/app/helpers/helo_helper.rb
module HeloHelper
end

RailsApp/app/helpers/people_helper.rb
module PeopleHelper
end

RailsApp/app/helpers/questionaries_helper.rb
module QuestionariesHelper
end

RailsApp/app/views/questionaries/_form.html.erb
<%= form_with(model: questionary, local: true) do |form| %>
  <% if questionary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(questionary.errors.count, "error") %> prohibited this questionary from being saved:</h2>

      <ul>
        <% questionary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.datetime_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/questionaries/edit.html.erb
<h1>Editing Questionary</h1>

<%= render 'form', questionary: @questionary %>

<%= link_to 'Show', @questionary %> |
<%= link_to 'Back', questionaries_path %>

RailsApp/app/views/questionaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>アンケートしよう！</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>期間</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% dx = 60 * 60 * 9 %>
    <% @questionaries.each do |questionary| %>
      <tr>
        <td><%= questionary.title %></td>
        <td><%= 'あと、約' + ((questionary.deadline - DateTime.now - dx) / (60 * 60 * 24)).to_i.to_s + '日' %>
        <% if questionary.deadline - dx > DateTime.now then %>
          <span class="not_finished">受付中</span>
          </td>
          <td><%= link_to 'アンケートを表示', questionary %></td>
        <% else %>
          <span class="finished">終了</span>
          </td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいアンケートを作る', new_questionary_path %>

RailsApp/app/views/questionaries/new.html.erb
<h1>新しいアンケートの作成</h1>

<%= render 'form', questionary: @questionary %>

<%= link_to 'Back', questionaries_path %>

RailsApp/app/views/questionaries/show.html.erb
<p id="notice"><%= notice %></p>
<h1 class="title"><%= @questionary.title %></h1>
<div class="questionary">
<p class="description">
  <%= @questionary.description %>
</p>

<p class="deadline">
  <strong>締めきり:</strong>
  <%= @questionary.deadline %>
</p>
</div>

<div class="items">

<%= form_tag(action:'show', id:@questionary.id) %>

<% count_items = 0 %>

<% @questionary.questionary_item.each do |item| %>
  <p class="q"><%= item.content %></p>
  <% count_items += 1 %>
  <% count_choices = 0 %>

  <% item.questionary_choice.each do |choice| %>
    <% count_choices += 1 %>

    <div class="choice">
      <input type="radio" id="<%= count_items.to_s + '_' + count_choices.to_s %>"
        name="r<%= count_items.to_s %>" value="<%= choice.value %>">
      <label for="<%= count_items.to_s + '_' + count_choices.to_s %>">
        <%= choice.content %></label></div>
  <% end %>
  <hr>
<% end %>

<%=submit_tag '送信' %>

</form>

</div>

<%= link_to 'Back', questionaries_path %>