RailsApp/config/routes.rb
Rails.application.routes.draw do
  resources :board_messages
  resources :board_users
  resources :data_pages
  devise_for :accounts
  get 'ajax/index'
  get 'ajax/data'
  post 'ajax/data'
  resources :questionary_results
  resources :questionary_choices
  resources :questionary_items
  resources :questionaries
  resources :answers
  resources :questions
  resources :mycontacts

  get 'questionary_results/calc/:id', to: 'questionary_results#calc'
  get 'questionary_choices/new/:id', to: 'questionary_choices#new'
  get 'questionary_items/new/:id', to: 'questionary_items#new'
  post 'questionaries/:id', to: 'questionaries#sendform'

  get 'blogs/index'
  get 'blogs', to: 'blogs#index'
  get 'blogs/:page', to: 'blogs#index'

  get 'blogs/genre/:id', to: 'blogs#genre'
  get 'blogs/genre/:id/:page', to: 'blogs#genre'

  get 'blogs/show/:id', to: 'blogs#show'

  get 'blogposts/index'
  get 'blogposts', to: 'blogposts#index'

  get 'blogposts/delete/:id', to: 'blogposts#delete'
  post 'blogposts/delete', to: 'blogposts#delete'
  post 'blogposts/delete/:id', to: 'blogposts#delete'

  get 'blogposts/add'
  post 'blogposts/add'

  get 'blogposts/:id', to: 'blogposts#edit'
  patch 'blogposts/:id', to: 'blogposts#edit'

  get 'blogposts/delete'

  get 'bloggenres/index'
  get 'bloggenres', to: 'bloggenres#index'

  get 'bloggenres/add'
  post 'bloggenres/add'

  get 'bloggenres/:id', to: 'bloggenres#edit'
  patch 'bloggenres/:id', to: 'bloggenres#edit'

  get 'blogconfigs/index'
  get 'blogconfigs', to: 'blogconfigs#index'

  get 'blogconfigs/edit'
  patch 'blogconfigs/edit'


  get 'messages/index'
  get 'messages', to: 'messages#index'
  get 'messages/add'
  post 'messages/add', to: 'messages#create'
  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'
  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'
  get 'cards/add'
  post 'cards/add'
  get 'cards/:id', to: 'cards#show'
  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'
  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/find'
  post 'people/find'
  get 'people/delete/:id', to: 'people#delete'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people', to: 'people#index'
  get 'people/index'
  get 'people/:id', to: 'people#show'

  get 'dengonban/index'
  post 'dengonban/index'
  get 'dengonban', to: 'dengonban#index'
  post 'dengonban', to: 'dengonban#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'helo/index'
  get 'helo', to: 'helo#index'
  get 'helo/other'
  post 'helo', to: 'helo#index'
  post 'helo/index'
  get 'helo/login_check'
end

RailsApp/app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

RailsApp/app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question

    validates :content, :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/blogconfig.rb
class Blogconfig < ApplicationRecord
    validates :title, :stylename, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/bloggenre.rb
class Bloggenre < ApplicationRecord
    has_many :blogpost

    validates :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/blogpost.rb
class Blogpost < ApplicationRecord
    belongs_to :bloggenre

    validates :title, :content, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/board_user.rb
class BoardUser < ApplicationRecord
    belongs_to :account
    has_many :board_message

    validates :nickname, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/card.rb
class Card < ApplicationRecord
end

RailsApp/app/models/data_page.rb
class DataPage < ApplicationRecord
end

RailsApp/app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator

    def validate_each(record, attribute, value)
        unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            record.errors[attribute] << (options[:message] || "is not an email")
        end
    end
end

RailsApp/app/models/message.rb
class Message < ApplicationRecord
    validates :message, presence: {message:'を書いてください。'}
end

RailsApp/app/models/mycontact.rb
class Mycontact < ApplicationRecord
    validates :name, presence: {message:'は、必須項目です。'}
    validates :age, numericality: {message:'は、数字で入力ください。'}
    validates :nationality, inclusion: {in: [true, false], message:'は、真偽値です。'}
end

RailsApp/app/models/person.rb
class Person < ApplicationRecord
    has_many :message

    validates :name, presence: {message: 'は、必須項目です。' }
    validates :age, numericality: {message: 'は、数字で入力ください。'}
    validates :mail, email: {message: 'はメールアドレスではありません。'}
end

RailsApp/app/models/question.rb
class Question < ApplicationRecord
    has_many :answer

    validates :content, :name, presence: {message:'は、必須項目です。'}
end

RailsApp/app/models/questionary.rb
class Questionary < ApplicationRecord
    has_many :questionary_item
    has_many :questionary_result

    validates :title, :description, :deadline, presence: {message:'は、必須項目です。'}
end

RailsApp/app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :set_board_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!

  # GET /board_messages
  # GET /board_messages.json
  def index
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    users = BoardUser.where 'account_id == ?', current_account.id
    if users[0] == nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where 'account_id == ?', current_account.id
    end
    @board_user = users[0]
    @board_message = BoardMessage.new
    @board_message.board_user_id = @board_user.id
  end

  # GET /board_messages/1
  # GET /board_messages/1.json
  def show
    redirect_to '/board_messages'
  end

  # GET /board_messages/new
  def new
    redirect_to '/board_messages'
  end

  # GET /board_messages/1/edit
  def edit
    redirect_to '/board_messages'
  end

  # POST /board_messages
  # POST /board_messages.json
  def create
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    @board_message = BoardMessage.new(board_message_params)
    @board_user = BoardUser.where('account_id == ?', current_account.id)[0]

    respond_to do |format|
      if @board_message.save
        format.html { redirect_to '/board_messages' }
        format.json { render :show, status: :created, location: @board_message }
      else
        format.html { render :index }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_messages/1
  # PATCH/PUT /board_messages/1.json
  def update
    redirect_to '/board_messages'
  end

  # DELETE /board_messages/1
  # DELETE /board_messages/1.json
  def destroy
    redirect_to '/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_message
      @board_message = BoardMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_message_params
      params.require(:board_message).permit(:content, :board_user_id)
    end
end

RailsApp/app/helpers/ajax_helper.rb
module AjaxHelper
end

RailsApp/app/helpers/answers_helper.rb
module AnswersHelper
end

RailsApp/app/helpers/blogs_helper.rb
module BlogsHelper
end

RailsApp/app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

RailsApp/app/helpers/cards_helper.rb
module CardsHelper
end

RailsApp/app/helpers/helo_helper.rb
module HeloHelper
end

RailsApp/app/helpers/people_helper.rb
module PeopleHelper
end

RailsApp/app/views/board_messages/_form.html.erb
<%= form_for(board_message) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_message.errors.count, "error") %> prohibited this board_message from being saved:</h2>

      <ul>
        <% board_message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<table>
  <tr class="field">
    <th><%= form.label :content %></th>
    <td><%= form.text_area :content, cols:40, row:3 %></td>
  </tr>

  <tr class="field">
    <th><%= form.label :board_user_id %></th>
    <td><%= @board_user.nickname %><%= form.hidden_field :board_user_id %></td>
  </tr>

  <tr class="actions">
    <th></th><td><%= form.submit %></td>
  </tr>
</table>
<% end %>

RailsApp/app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

RailsApp/app/views/board_messages/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Message Board</h1>
<%= render 'form', board_message: @board_message %>
<p><%= link_to 'go home >>', controller: :board_users %></p>
<hr>
<h2>※Posted Messages.</h2>

<table width="90%">
  <thead>
    <tr>
      <th>Content</th>
      <th width="150px">Board user</th>
    </tr>
  </thead>

  <tbody>
    <% @board_messages.each do |board_message| %>
      <tr>
        <td><%= board_message.content %></td>
        <td><%= link_to board_message.board_user.nickname, controller: :board_users, action: :show, id: board_message.board_user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div><%= paginate @board_messages %></div>
<hr>

RailsApp/app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

RailsApp/app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>